sudo: required
services:
  - docker
before_install:
  - docker build -f dev.Dockerfile -t jnaputi/reactive-docker .
script:
  - docker run -e CI=true jnaputi/reactive-docker npm run test -- --coverage
