version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /usr/apps/reactive-docker/node_modules/'
      - .:/usr/apps/reactive-docker
